### ISSUE TITLE
Fullscreen preview does not show configurations, just defaults

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#104]
The main purpose of the full screen preview is to configure a widget and then send a link with that configuration to someone. To showcase what is possible. However, the full screen preview takes only the default config from the manifest file. 

Related issues (possible duplicates, just for reference):
- #151 
- #150

**Comment by Piiit** [comment]
@maximiliannocker @danielecanu 
I can see changed configurations now, but I am unable to send a link to someone with that configuration. It is only stored locally.

The main purpose of this feature is to configure a component and then send it as preview example to someone. So we need a URL that encodes those configurations.

**Comment by Piiit** [comment]
@SirCotare An idea: Maybe we could use a POST method similar to the createsandbox one, where we send the snippet etc. and have something persisting that. Then create a hash in the URL to be send... 

The old solution with url encoding has some issues with complex configuration strings. 

Could that be a solution? Is it too much work? Or, maybe less work?

**Comment by Piiit** [comment]
Tested with "Parking" and got the following URL to copy `https://webcomponents.opendatahub.testingmachine.eu/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff/fullscreen?attribs=P2F0dHJpYnM9d2lkdGg9IjEwMCUyNSI7aGVpZ2h0PSIxMDAlMjUiO2N1cnJlbnRMb2NhdGlvbj0iJyU3QiI7ImxhdCI6OyJsYXQiOjQ2LjMxLDsibGF0Ijo0Ni4zMSwibG5nIjo7ImxhdCI6NDYuMzEsImxuZyI6MTEuMjY7ImxhdCI6NDYuMzEsImxuZyI6MTEuMjZ9JzsibGF0Ijo0Ni4zMSwibG5nIjoxMS4yNn0nem9vbT0iMTAiO21hcEF0dHJpYnV0aW9uPSIlMjZjb3B5JTNCJTIwJTNDYSUyMGhyZWYlM0QnaHR0cHMlM0ElMkYlMkZvcGVuc3RyZWV0bWFwLm9yZyUyRmNvcHlyaWdodCclM0VPcGVuU3RyZWV0TWFwJTIwY29udHJpYnV0b3JzJTNDJTJGYSUzRSI7dGlsZXMtdXJsPSJodHRwcyUzQSUyRiUyRiU3QnMlN0QudGlsZS5vcGVuc3RyZWV0bWFwLm9yZyUyRiU3QnolN0QlMkYlN0J4JTdEJTJGJTdCeSU3RC5wbmciO2Rpc2FibGVQYXJraW5nRm9yZWNhc3Q7ZGlzYWJsZVBhcmtpbmdGb3JlY2FzdGZvbnRGYW1pbHk9Im1vbm9zcGFjZSI7bGFuZ3VhZ2U9Iml0Ijs%3D`

which resulted in a 400 Bad Request

**Comment by SirCotare** [comment]
the issue should be resolved. all attribs are now base64 encoded for transport.

fyi: the issue was already there on v1 of the store: https://webcomponents.opendatahub.bz.it/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff <- broken external window link

**Comment by Piiit** [comment]
@SirCotare Yes we were aware of that, and we discussed that also during one of our meetings... you said, that you might find a better solution back then.

I updated the main comment section, we will then close this issue together with the other bugs related to the fullscreen preview.

**Comment by Piiit** [comment]
The sending and fullscreen preview works, the propagating of the configuration not --> see #151 

I close this, and we continue on the other issue
