### ISSUE TITLE
Lighthouse stats not shown, but present in the database

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#105]
I see that the lighthouse scheduler works and imports results into the database, but they are not shown inside the web app.

Even though the API call shows them as json response.

**Comment by SirCotare** [comment]
Lighthouse stats are gathered on a per-webcomponent-version basis. The frontend however just displays the stats for the latest version of a webcomponent.

So it could be that the system was unable to benchmark the latest version at all, or that the stats were not yet available at the time you visited the page.

If this explaination does not resolve the issue, please provide an example so I may look into the matter further.

**Comment by sseppi** [comment]
As agreed in the meeting we try to show the statistics of the selected version of the Web Component. Moreover it has been decided to rename the "current version" label into "latest version".

**Comment by Piiit** [comment]
Seems to work, otherwise we will open new issues in the future...
