### ISSUE TITLE
As a maintainer of the web component store, I want to have everything on docker

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#110]
Belongs to #88 

TODOS
- [x] local docker development
  - [x] api
  - [x] cdn
  - [x] webapp
  - [x] local postgres
  - [x] local smtp test (mailhog)
  - [x] local development readme update for docker
- [x] docker for testingmachine
  - [x] api
  - [x] cdn
  - [x] webapp (it is a S3 bucket)
  - [x] smtp integration for testing
  - [x] keycloak integration (incl. cli tool tests)
  - [x] missing api calls to upload files to the CDN #118
  - [x] fix legacy automatic deployment
  - [x] fix CI
- [x] docker on production
  - [x] api
  - [x] cdn
  - [x] webapp (it is a S3 bucket)
  - [x] smtp integration for production
  - [x] keycloak integration
  - [x] persitence layer of the workspace (js files, manifest and icons)
  - [x] elastic logging / kibana / grafana
  - [x] fix CI
- [x] cleanup remaining tomcat + jenkins configs and installations

Externalized:
- API: swagger base url configurability #112 

Postponed:
- Parity between local development and other stages (non-root execution) --> Jenkins pipeline: fix .m2 caching (permission problem) #114
- cli tool and automatic deployment on testingmachine (#116)

**Comment by Piiit** [comment]
@dulvui Could you tick what has been done already and eventually close the issue

**Comment by dulvui** [comment]
Everything done now
