### ISSUE TITLE
api: probably missing feature: Can't find the upload file API call to post dist files into our CDN

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#118]
Please ignore this if you have planned this already for a later development cycle.

**Comment by SirCotare** [comment]
You and create and update webcomponent versions via the data service's API.

webcomponent-version-admin-controller
-> POST: create a new version
-> PUT: replace a version

both routes allow you to upload the files in a base64 encoded format:
`"distFiles": [
    {
      "fileName": "string",
      "fileDataBase64": "string"
    }
  ],`

**Comment by Piiit** [comment]
@SirCotare Thanks for the explanation... This works
