### ISSUE TITLE
Issue with External Window feature

### ISSUE THREAD

**Issue by iceeye2017** [noi-techpark/it.bz.opendatahub.webcomponents#122]
**Describe the issue**
5 web-components do not support the feature "External Window". When trying to open them a error message is thrown instead.

Webcomponents:
* Parking:
  *    https://webcomponents.opendatahub.bz.it/webcomponent/543ed85d-8280-4240-8625-4ee5102710ff?from=%2Fsearch%2Fany%2Fparking
* Mountain Area:
  *   https://webcomponents.opendatahub.bz.it/webcomponent/430eead9-0bbc-4832-b4c0-78236d77a36b?from=%2Fsearch%2Fany%2Fmountain
* Gastronomies:
   *   https://webcomponents.opendatahub.bz.it/webcomponent/f113a6c6-445f-4633-a901-b8004353c903?from=%2Fsearch%2Fany%2Fgastr
* Events:
  *   https://webcomponents.opendatahub.bz.it/webcomponent/1cba7d30-8331-4b4a-b528-c4e03279365c?from=%2Fsearch%2Fany%2FEvents
 * Generic Meteorology:
   *   https://webcomponents.opendatahub.bz.it/webcomponent/8ed52ba6-ce1d-45c8-83bb-062d688b4326?from=%2Fsearch%2Fany%2FGeneric

**To Reproduce**
1. Go to the mentioned web-components or links
2. Click on "EXTERNAL WINDOW"
3. See error message 

**Expected behavior**
Fullscreen view of component

**Screenshots**
Screenshot of displayed error message
![BadRequest](https://user-images.githubusercontent.com/84740021/120783693-90e31980-c52b-11eb-9a6e-e6ae62a79547.PNG)

**Desktop**
 - OS: Windows 10
 - Browser Chrome, Firefox

**Additional context**
See: https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters
Could be the cause of the problem.

**Comment by Piiit** [comment]
@iceeye2017 Thanks for your feedback... we are currently developing a new version of this store... please see https://webcomponents.opendatahub.testingmachine.eu/ for details... The new store should no longer have those issues with parameter encoding inside the URL.

**Comment by Piiit** [comment]
Update: We decided that this needs to be fixed for the old version as well, because v2 is still not ready

**Comment by Piiit** [comment]
@ohnewein @sseppi We forgot about this today... I'll add it now...

**Comment by Piiit** [comment]
@ohnewein @sseppi Since this seems to be not that easy to fix, and the v2 should now finally really be close ... I could just remove the button in the meantime. What do you think?

**Comment by sseppi** [comment]
If the v2 fixes this bug I think we could hide the button hoping that in a short time we have the v2 online.

**Comment by Piiit** [comment]
Done, I removed that button for the moment...
