### ISSUE TITLE
ci and test deployment: error during testing

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#126]
See https://ci.opendatahub.bz.it/job/it.bz.opendatahub.webcomponents-store/job/development/164/console for example

**UPDATE 2021-06-28** Tests have been fixed

Thx for your work, just some suggestions/questions:

- What do we test here exactly?
- Do we need something configured to have the Google Light House tests work?
- Are they integration tests (and thus not unit tests)?
> FYI: On our CI we do not allow any credentials or API keys, please make all unit tests work without credentials, and mark all integration tests as such... so we can run them with `mvn verify` instead.

Finally, please test only the code and services you develop (or were part of a former development), we do not need to test external tools.

@Sircotare please accept the invitation I've send you this moment

**Comment by SirCotare** [comment]
The failing test should be fixed and was already merged.

To answer your questions:
* We are testing if the (our) code that interacts with the lighthouse api does what it whould.
* You don't need to configure anything.
* These are unit tests. The "RestTemplate" that would be used to actually make the API calls is mocked. We are testing the subject-under-test in isolation.

Finally, we are only testing our own code. Not external tools.

PS: Thanks for the invite, it seems this finally worked now.

**Comment by Piiit** [comment]
@SirCotare Thanks for clarification

**Comment by Piiit** [comment]
@SirCotare I fixed now also the CI pipeline...
