### ISSUE TITLE
v2 webapp: Several regressions

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#128]
Please see https://webcomponents.opendatahub.testingmachine.eu

- [ ] Filtering, 
- [ ] searching and 
- [ ] page switching no longer works
- [ ] Some thumbnails are not loading
- [x] changing to an older version in detail view no longer works
- [ ] The store seems to be less responsive as v1 (might be subjective)

... maybe there are other things as well, please have a detailed look into all corners and see what comes up. 

Please try to test for regressions before sending another PR, otherwise the feedback round turns in circles...

Thanks for your understanding

FYI
@sseppi @danielecanu @maximiliannocker @sircotare

**Comment by SirCotare** [comment]
I have reviewed the issues. Unfortunately I was unable to reproduce any the problems except one on localhost.

The issue when switching versions will be fixed in a pull request very soon.

The other issues are all related to your API sending (random?) 503 (service unavaiable) respones or invalid CORS headers. Both seem to be related to your deployment. I'm not sure if there is anything we can to without having access to any logs and such.

Are there any security filters running? Rate limiter, WAF, etc?

**Comment by Piiit** [comment]
@SirCotare I will try to reproduce the errors locally and report back.... It could be that it is a proxy problem... thx for your investigations.

> Are there any security filters running? Rate limiter, WAF, etc?

No... no such things are installed.

**Comment by Piiit** [comment]
@SirCotare @sseppi @danielecanu 
I managed to pinpoint the issue, it was related to the jre-8-alpine docker image. We got segfaults, the spring boot application crashed and restarted, therefore we had a slow API response, because the restart took some seconds....
I changed now to jre-8 and we no longer get segfaults, but I did not find the real issue. We use alpine images in most other java APIs and never had such problems. 

Starting the local development with docker-compose also showed the issue immediately, but only for some API calls. One such call is the thumbnail download for the VKG web component, which uses a webp image... dunno if that is related.
Now hopefully those things do not happen again, if so, please test on your local machine with `docker-compose up` and a .env file... 

@SirCotare Thanks for your time to get this solved, and my apologies as I thought it was related to your last PRs... 

I close this issue now... we will reopen it if segfaults happen again... 

Thanks to all!
