### ISSUE TITLE
New Open Data Hub CI

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.webcomponents#137]
In order to align the Web Component store to the new Open Data Hub CI the following changes to the design should be made:
- [x] replace the Open Data Hub with the black and white one
- [x] put the NOI black and white logo top right as in the Open Data Hub webpage (see https://opendatahub.bz.it/)
- [x] change the Favicon and put the one of NOI
- [x] change green color to dark green ( R 80 | G 116 | B 47 ) Hex #50742F

**Comment by Piiit** [comment]
@SirCotare The NOI logo (point 2) is missing

**Comment by SirCotare** [comment]
@Piiit I added it now. Sorry. This was a misunderstanding on our end. We obviously were not aware that there are two logos now.

**Comment by Piiit** [comment]
Thanks
