### ISSUE TITLE
“Filter by categories” jumps back after selecting a filter item

### ISSUE THREAD

**Issue by lukmay** [noi-techpark/it.bz.opendatahub.webcomponents#142]
When customizing the filter by categories with multiple filter items, it always jumps back after one was selected, so the use is forced to open in again for every new Item.

**UPDATE**
The main feature request (it was a nice-to-have) has been fulfilled, but there is a bug now...

Bug is as follows (see comments below for more details): 
- search is initiated on the index page
- the index page redirects to the search page which effectively re-renders the view
- The collapse should work properly when you are already on the search page to begin with, but not on the frontpage

**Comment by Piiit** [comment]
@danielecanu This is a nice-to-have if you find the time...

**Comment by Piiit** [comment]
Thanks that you took even this issue :-)

**Comment by Piiit** [comment]
@SirCotare I am sorry, but we have to open this again, because on the very first page loading selecting only the very first filter option the dropdown closes. This does not happen in subsequent trials....

Please test it with a fresh private browsing window.

**Comment by SirCotare** [comment]
@Piiit that happens when a search is initiated on the index page. the index page redirects to the search page which effectively re-renders the view. I fear that there is no "easy" fix for this.
The collapse should work properly when you are already on the search page to begin with.

**Comment by Piiit** [comment]
@SirCotare @sseppi @lukmay @danielecanu Works, thanks
