### ISSUE TITLE
Konfiguration of Swagger (https://cdn.webcomponents.opendatahub.testingmachine.eu) runs on localhost not on the Testingmachine

### ISSUE THREAD

**Issue by lukmay** [noi-techpark/it.bz.opendatahub.webcomponents#155]
The Swagger (https://cdn.webcomponents.opendatahub.testingmachine.eu) runs the Calls on "http://localholst:8080" instead of the 
"https://api.webcomponents.opendatahub.testingmachine.eu".

**Comment by Piiit** [comment]
@SirCotare Is the CDN swagger host configurable?

**Comment by SirCotare** [comment]
@Piiit it should be. see: **application.swaggerBaseUrl**

**Comment by Piiit** [comment]
@SirCotare Sorry, you are right, you implemented that also for the CDN. Thx
