### ISSUE TITLE
Remove the content from the webapp that is not ready yet

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#166]
- [ ] Remove Carousel
- [ ] Footer with 4 images
- [ ] Change menu layout so that it is aligned with the content below
- [ ] Adapt the menu + burger (remove the following items):
     - Contribute
     - Make Use
     - Community
     - About
     - FAQ 

With "remove" we mean comment-out, so that we can reactivate it easily later.

**Comment by RudiThoeni** [comment]
please check and close when done ;)
