### ISSUE TITLE
Update all web components with the new API calls (via a new CLI or API calls directly)

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#167]
README breaks preview of wemcomponents store, so its currently hidden

- [x] Update all stats of all web components (lighthouse + size)
- [x] Link to the README
- [x] License information for each web component (info coming from the `wcs-manifest.json` file)

Here we need to decide if we want create a CLI tool as wrapper around the API to be used inside the future CD pipelines... maybe Github Actions or something else.

https://api.webcomponents.opendatahub.testingmachine.eu/
https://cdn.webcomponents.opendatahub.testingmachine.eu/

Example: https://github.com/noi-techpark/webcomp-recipe/blob/master/wcs-manifest.json

**Comment by Piiit** [comment]
@mmalfertheiner This has been done by @dulvui

**Comment by dulvui** [comment]
Done with version 2 of webcomponent store and cli
