### ISSUE TITLE
Create a CD for a web component with GitHub Actions

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#168]
Choose a web component (for example, https://github.com/noi-techpark/webcomp-recipe) and publish it on testing on each push to development branch, and when we get a semver tag on the main branch. Use the new CLI or API calls for it, update the readme, license info and manifest info, and publish dist files to the CDN... all done with API calls.

At the same time, test the API calls, which were only used for short tests until now.

This is a test to see if Github Actions could be a valuable replacement for Jenkins...

**Comment by Piiit** [comment]
@dulvui I think you did this already, can we close it?

**Comment by dulvui** [comment]
Yes done and closing now.
