### ISSUE TITLE
EPIC: As a maintainer of the web components and store, I need a CLI tool to easily deploy and manage components in a CD pipeline

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#175]
The API allows already all these things, but a CLI tool would facilitate the usage of the API in pipeline scripts

**Comment by dulvui** [comment]
A simple CLI tool is implemented that can push (create, update), delete and list all webcomponents int testing and production environment (not all possible API calls are implemented):
https://github.com/noi-techpark/it.bz.opendatahub.webcomponents/tree/main/webcompstore-cli
It is already integrated in the webcom-push Github Action that automatically pushes webcomponentns to the store:
https://github.com/noi-techpark/github-actions/tree/main/webcomp-push
