### ISSUE TITLE
The crawler does not download all web components, when a single import fails

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#60]
It stops all crawling, when a single exception occurs

The problem is that an UUID on the origins file for the same web component should never be changed within the same git history. That is, the skiarea web component had once an UUID 123 and later it got changed to 456, which is not allowed. The crawler gets an exception, and stops handling subsequent sources in the origins list.

I will keep this bug open nevertheless, because we need:
1) better error reporting if a web component version got imported or not
2) a more robust crawler, that just skips errors and handles correct entries nevertheless
3) better information logging, which component got handled and which not

**Comment by dulvui** [comment]
Deprecated with version 2 of the webcomponent store.
No crawler is need anymore
