### ISSUE TITLE
Infrastructure: Insertion of a new web component should be easy in a single pipeline; on testing fully automatic for each branch HEAD

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#80]
@bertolla's comment about the deployment pipeline of web components:
I did so, it works, but you still need to do things manually, which results in you going back and forth between failing pipelines and fixing stuff. I mean maybe the tagging could be done here and also the adding of the repo to valid origins.

We should automatically deploy HEADs of each branch to testingmachine, without tagging and fully automatic. So we should have all tags and all heads as drop down on webcomponents.opendatahub.testingmachine.eu

**Comment by dulvui** [comment]
With Github Actions we have automatic deployment pipelines for testing and production
