### ISSUE TITLE
As a web component store user I want all Web Component named without the "Web Component" wording.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.webcomponents#90]
- [x] Mountain Area: https://github.com/noi-techpark/webcomp-mountain-area/blob/development/wcs-manifest.json
- [x]  NOI Maps: https://github.com/noi-techpark/webcomp-maps-noi/blob/development/wcs-manifest.json
- [x]  Creative Industries: https://github.com/noi-techpark/webcomp-creative-industries/blob/development/wcs-manifest.json
- [x] Events: https://github.com/noi-techpark/webcomp-events/blob/development/wcs-manifest.json
- [x]  Gastronomies: https://github.com/noi-techpark/webcomp-gastronomies/blob/development/wcs-manifest.json
- [x]  Genreic Meteo https://github.com/noi-techpark/webcomp-meteo-generic/blob/development/wcs-manifest.json
- [x]  Parking: https://github.com/noi-techpark/webcomp-parking/blob/development/wcs-manifest.json
- [x] Activity - POI: https://github.com/noi-techpark/webcomp-activity-poi/blob/development/wcs-manifest.json
- [x]  ONLY TESTING!! Mobility Traffic: https://github.com/noi-techpark/webcomp-mobility-traffic/blob/development/wcs-manifest.json

**Comment by sseppi** [comment]
I've changed the naming in the manifest file of the following web components:

- Moountain Area: https://github.com/noi-techpark/webcomp-mountain-area/blob/development/wcs-manifest.json
- NOI Maps: https://github.com/noi-techpark/webcomp-maps-noi/blob/development/wcs-manifest.json
- Creative Industries: https://github.com/noi-techpark/webcomp-creative-industries/blob/development/wcs-manifest.json
- Events: https://github.com/noi-techpark/webcomp-events/blob/development/wcs-manifest.json
- Gastronomies: https://github.com/noi-techpark/webcomp-gastronomies/blob/development/wcs-manifest.json
- Genreic Meteo https://github.com/noi-techpark/webcomp-meteo-generic/blob/development/wcs-manifest.json
- Parking: https://github.com/noi-techpark/webcomp-parking/blob/development/wcs-manifest.json
- Activity - POI: https://github.com/noi-techpark/webcomp-activity-poi/blob/development/wcs-manifest.json
- Mobility Traffic: https://github.com/noi-techpark/webcomp-mobility-traffic/blob/development/wcs-manifest.json

Please test all the web component and put it in production.
Plese note that the Mobility Traffic web component is still in testing and there we need a go from Roberto before to go online.

**Comment by ohnewein** [comment]
Should this name changes be visible on testingmachine? I cannot see the changes there.

**Comment by Piiit** [comment]
@ohnewein The web component pipelines are only semi-automatic... that is still in development by themselves, so at the moment we still need to tag the git branch and manually deploy them afterwards, but that final step is then already automatic... I would need approx. 3 days to write the whole pipeline, but since the store 2.0 is on the way most of that work will be done in the API itself, so I would wait until then

**Comment by ohnewein** [comment]
@Piiit that's fine for me. 

I will not be able to contribute testing as long as someone will not deploy the web components somewhere.

**Comment by Piiit** [comment]
@ohnewein I will ping you when it is online, so you can test it...

**Comment by Piiit** [comment]
@ohnewein @sseppi
I changed my mind, since this is a lot of manual work, I decided to give it a try to implement the pipeline in a very simple way only. When we have the new store api, we can then switch to the new one...

**Comment by Piiit** [comment]
@sseppi @ohnewein @rcavaliere All done, except Mobility Traffic, which will follow on Monday ... Have a nice weekend!
