### ISSUE TITLE
As a web component developer/store manager I want to have a automatic test deployment to see changes immediately

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#91]
BLOCKED: waiting for version 2.0 of Web Component Store 

This is related to the issue #90. 

All the web components that were not in that issue should be migrated, otherwise they will not be automatically deployed on testing when we push changes to the development branches.

Burning down this problem. See progress here (webcomp-* rows) --> 
https://docs.google.com/spreadsheets/d/1txvRdrpv2bjt1HsDjCAh-7s3V2iT7QCqVxbxFr59JRA/edit#gid=2033769176

Need to solve #118 before going ahead with automatic deployments for v2 via CLI.... but the legacy deployment can still work until we have a full functioning CDN API that can also upload files.

**Comment by dulvui** [comment]
The version 2 of webcomponent store has now a cli for the API and automated Github Actions pipelines to publish on testing and production environment automatically.
